name: Quality

# Run this workflow every time a commit is pushed to feature/*
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/ylunch/YnovYLunch
        azure-pipeline-name: 'YnovYLunch-.NET Core with SonarCloud-CI'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
